### ISSUE TITLE
Frequncy counter threshold value selection

### ISSUE THREAD

**Issue by parveennisha** [apotocnik/redpitaya_guide#4]
Hi Anton,
I am trying to understand your frequency counter project. In frequency counter code part you have assigned -100 and -150 for threshold values. I wanted to know from what basis you are assigning this threshold.

**Comment by apotocnik** [comment]
Dear Abinaya

In the current project the threshold values are hard-coded in the .bit file. One can of course modify the FPGA program in Vivado and make it programmable. I would do it in the same way as the Ncycles parameter. However, for that you would need another GPIO IP or use Pavel's configurations ip core to set all the variables as mentioned in the fifth project.
The current threshold values are set close to 0 V when converted form the 14-bit ADC value. Depending on your jumper settings on the board the maximal values are:

+/- 2^(14-1) = +/-8192 corresponds to +/-1 V for LV or +/-23 V for HV jumper setting.

I aimed for threshold to be exactly at zero, however, when working with the averager FPGA program I realized that 0V corresponds to roughly -100 ADC value due to a small dc drift of the ADC.

I hope this helps you continue your project.

Best
